version: 0.0
os: linux
files:
  - source: utils/scripts/deployment/install
    destination: /opt/codedeploy-agent/deployment-root/gloagen-app/install
permissions:
  - object: /opt/codedeploy-agent/deployment-root/gloagen-app/install
    pattern: "*.py"
    mode: 774
    owner: gloag