version: 0.0
os: linux
files:
  - source: utils/scripts/deployment/properties
    destination: /opt/codedeploy-agent/deployment-root/gloagen-app/properties
  - source: utils/scripts/deployment/housekeep
    destination: /opt/codedeploy-agent/deployment-root/gloagen-app/scripts/housekeep
permissions:
  - object: /opt/codedeploy-agent/deployment-root/gloagen-app
    owner: gloag
    pattern: "*.*"
    mode: 764