version: 0.0
os: linux
files:
  # - source: deployment/userservice/properties/release.yml
  #   destination: /opt/server/deployment/properties/
    - source: utils/scripts/deployment/housekeep/
      destination: /opt/server/deployment/scripts
permissions:
  - object: /opt/server/deployment/scripts
    owner: gloag
    pattern: "*.*"
    mode: 764
#hooks:
 # BeforeInstall:
  #  - location: /opt/server/deployment/scripts/houseKeep_clean-release-spec.sh
   #   runas: gloag
 # AfterInstall:
  #  - location : /opt/server/deployment/scripts/deploy.py
   #   runas: gloag