version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: deployment/scripts/stop-wildfly.sh
    - location: deployment/scripts/apply-local-ip.py
  ApplicationStart:
    - location: deployment/scripts/start-wildfly.sh
      runas: wildfy
