version: 0.0
os: linux
files:
   - source: deployment/userservice/properties/release.yml
     destination: /opt/server/deployment/properties/
permissions:
  - object: /opt/server/deployment/properties
    owner: gloag
    pattern: "*.*"
    mode: 464
hooks:
  AfterInstall:
    - location : /opt/server/deployment/scripts/deploy.py
      runas: gloag