version: 0.0
os: linux
files:
  - source: deployment/
    destination: /opt/codedeploy-agent/deployment-root/gloagen-app
permissions:
  - object: /opt/codedeploy-agent/deployment-root/gloagen-app
    pattern: "*.*"
    mode: 774
    owner: gloag
hooks:
  AfterInstall:
    - location: ../../../gloagen-app/scripts/properties-env.sh
    #- location: /opt/server/deployment/scripts/deploy.py
      #runas: gloag