#!/usr/sh
GLOAG_DEPLOY_HOME=/opt/codedeploy-agent/deployment-root/gloagen-app
GLOAG_DEPLOY_LOGS_HOME=${GLOAG_DEPLOY_HOME}/logs
GLOAG_WEBAPPS_HOME=/opt/server/tomcat/webapps
GLOAG_DEPLOY_PROPERTIES_HOME=${GLOAG_DEPLOY_HOME}/properties
GLOAG_DEPLOY_RELEASE_HOME=${GLOAG_DEPLOY_HOME}/release/userservice
GLOAG_DEPLOY_RELEASE_PROPERTIES_HOME=${GLOAG_DEPLOY_RELEASE_HOME}/properties
GLOAG_DEPLOY_DOWNLOADS_HOME=${GLOAG_DEPLOY_HOME}/downloads